//meminta request data
GET http://localhost:5000/users

###
//membuat user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Haikal Azhar",
    "email": "haikal@gmail.com",
    "password": "123456",
    "confPassword":"123456",
    "role":"dosen"
}


###
///login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "haikal@gmail.com",
    "password": "123456"
}

###
//mengecek status login dan role loginnya sebagai apa
GET http://localhost:5000/me

###
// cek logout
DELETE  http://localhost:5000/logout

###
//liat materi
GET  http://localhost:5000/materis

###
//tambah materi
POST http://localhost:5000/materis
Content-Type: application/json

{
    "nama_materi" : "Materi 3",
    "link_materi" : "http://djawdjwaodjawdo.com",
    "mata_kuliah": "paw",
    "tenggat_waktu": "2022-12-26"
}

###
POST  http:/localhost:5000/jadwaldosen

###
PATCH  http://localhost:5000/materis/70b7e10e-e6f1-471b-817e-3937417ef7d1
Content-Type: application/json

{
    "nama_materi" : "Materi Updated",
    "link_materi" : "http://djawdjwaodjawdo.com",
    "mata_kuliah": "ppaw",
    "tenggat_waktu": "2022-12-25"
}

###
DELETE http://localhost:5000/materis/12984554-3382-4f6a-b3f3-94666ee6f97c
